In [10]:
#1 
try:
    n = int(input("Enter a positive integer:"))
    if n >0:
        for i in range(0,n):
            i = i ** 2
            print(i)
    else:
        print("Please a positive integer")
except:
        print("Please a positive integer")

Enter a positive integer:5
0
1
4
9
16

In [15]:
#2 
score = float(input("Enter a number:"))

if score > 0 and score <100:
    if score >= 90:
        print("A")
    elif score >= 80:
        print("B")
    elif score >= 70:
        print("C")
    elif score >= 60:
        print("D")
    else:
        print("F")
else:
    print("Bad Score")

Enter a number:101
Bad Score

In [26]:
#3
def leap_year(n):
    if n%4 == 0:
        if n%100 != 0:
            return True
        else:
            if n%400 == 0:              
                return True
            else:
                return False
    else:
        return True

print(leap_year(int(input("Enter a year:"))))

Enter a year:1900
False

In [9]:
#4
# Use the following code as a setup for this question. 
# If pandas, numpy, or matplotlip is not installed, please make sure to do so

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Turn off notebook package warnings
import warnings
warnings.filterwarnings('ignore')

# print graphs in the document
%matplotlib inline

#print graphs in ggplot style
plt.style.use('ggplot')

In [28]:
#(1)
open('gapminder.csv','r').readline()

'"continent","country","gdpPercap_1952","gdpPercap_1957","gdpPercap_1962","gdpPercap_1967","gdpPercap_1972","gdpPercap_1977","gdpPercap_1982","gdpPercap_1987","gdpPercap_1992","gdpPercap_1997","gdpPercap_2002","gdpPercap_2007","lifeExp_1952","lifeExp_1957","lifeExp_1962","lifeExp_1967","lifeExp_1972","lifeExp_1977","lifeExp_1982","lifeExp_1987","lifeExp_1992","lifeExp_1997","lifeExp_2002","lifeExp_2007","pop_1952","pop_1957","pop_1962","pop_1967","pop_1972","pop_1977","pop_1982","pop_1987","pop_1992","pop_1997","pop_2002","pop_2007"\n'

In [29]:
#(2)
data = pd.read_csv("gapminder.csv")
data = data[["continent","country","gdpPercap_2007","lifeExp_2007","pop_2007"]]
data

,continent,country,gdpPercap_2007,lifeExp_2007,pop_2007
0,Africa,Algeria,6223.367465,72.301,33333216
1,Africa,Angola,4797.231267,42.731,12420476
2,Africa,Benin,1441.284873,56.728,8078314
3,Africa,Botswana,12569.851770,50.728,1639131
4,Africa,Burkina Faso,1217.032994,52.295,14326203
5,Africa,Burundi,430.070692,49.580,8390505
6,Africa,Cameroon,2042.095240,50.430,17696293
7,Africa,Central African Republic,706.016537,44.741,4369038
8,Africa,Chad,1704.063724,50.651,10238807
9,Africa,Comoros,986.147879,65.152,710960
10,Africa,Congo Dem. Rep.,277.551859,46.462,64606759
11,Africa,Congo Rep.,3632.557798,55.322,3800610
12,Africa,Cote d'Ivoire,1544.750112,48.328,18013409
13,Africa,Djibouti,2082.481567,54.791,496374
14,Africa,Egypt,5581.180998,71.338,80264543
15,Africa,Equatorial Guinea,12154.089750,51.579,551201
16,Africa,Eritrea,641.369524,58.040,4906585
17,Africa,Ethiopia,690.805576,52.947,76511887
18,Africa,Gabon,13206.484520,56.735,1454867
19,Africa,Gambia,752.749726,59.448,1688359
20,Africa,Ghana,1327.608910,60.022,22873338
21,Africa,Guinea,942.654211,56.007,9947814
22,Africa,Guinea-Bissau,579.231743,46.388,1472041
23,Africa,Kenya,1463.249282,54.110,35610177
24,Africa,Lesotho,1569.331442,42.592,2012649
25,Africa,Liberia,414.507341,45.678,3193942
26,Africa,Libya,12057.499280,73.952,6036914
27,Africa,Madagascar,1044.770126,59.443,19167654
28,Africa,Malawi,759.349910,48.303,13327079
29,Africa,Mali,1042.581557,54.467,12031795
...,...,...,...,...,...
112,Europe,Belgium,33692.605080,79.441,10392226
113,Europe,Bosnia and Herzegovina,7446.298803,74.852,4552198
114,Europe,Bulgaria,10680.792820,73.005,7322858
115,Europe,Croatia,14619.222720,75.748,4493312
116,Europe,Czech Republic,22833.308510,76.486,10228744
117,Europe,Denmark,35278.418740,78.332,5468120
118,Europe,Finland,33207.084400,79.313,5238460
119,Europe,France,30470.016700,80.657,61083916
120,Europe,Germany,32170.374420,79.406,82400996
121,Europe,Greece,27538.411880,79.483,10706290
122,Europe,Hungary,18008.944440,73.338,9956108
123,Europe,Iceland,36180.789190,81.757,301931
124,Europe,Ireland,40675.996350,78.885,4109086
125,Europe,Italy,28569.719700,80.546,58147733
126,Europe,Montenegro,9253.896111,74.543,684736
127,Europe,Netherlands,36797.933320,79.762,16570613
128,Europe,Norway,49357.190170,80.196,4627926
129,Europe,Poland,15389.924680,75.563,38518241
130,Europe,Portugal,20509.647770,78.098,10642836
131,Europe,Romania,10808.475610,72.476,22276056
132,Europe,Serbia,9786.534714,74.002,10150265
133,Europe,Slovak Republic,18678.314350,74.663,5447502
134,Europe,Slovenia,25768.257590,77.926,2009245
135,Europe,Spain,28821.063700,80.941,40448191
136,Europe,Sweden,33859.748350,80.884,9031088
137,Europe,Switzerland,37506.419070,81.701,7554661
138,Europe,Turkey,8458.276384,71.777,71158647
139,Europe,United Kingdom,33203.261280,79.425,60776238
140,Oceania,Australia,34435.367440,81.235,20434176
141,Oceania,New Zealand,25185.009110,80.204,4115771

In [30]:
#(3)

data[["pop_2007"]].sum()

pop_2007    6251013179
dtype: int64

In [31]:
#(4)

data.groupby("continent").sum()[["pop_2007"]]

             pop_2007
continent
Africa      929539692
Americas    898871184
Asia       3811953827
Europe      586098529
Oceania      24549947